export const CONTROL_CENTER_CONSTANTS = {
    TELEMETRY_REFRESH_MS: 3000,
    FEED_REFRESH_MS: 5000,
    MAX_FEED_ITEMS: 10,
    CHART_HEIGHT_PX: 240,
    DAG_ANIMATION_SPEED_MS: 2000,
    SEED_INITIAL_STATE: 42,
} as const;
